name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu-clang-trinitycore:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.forgejo/actions/setup_ubuntu

      - name: Build tswow
        shell: bash
        run: npm run build noac